name: Integration

on:
  push:
    branches:
      - main

jobs:
  integration:
    name: "Integration tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Run integration tests
        env:
          MEDIATOR_URL: ${{ vars.SIT_MEDIATOR_URL }}
          AGENT_URL: ${{ vars.SIT_AGENT_URL }}
        run: |
          npm ci
          npm run integration

      - name: Dispatch publication
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: amagyar-iohk/integration
          event-type: edge-agent
          client-payload: '{"component": "edge-agent", "env": "sit"}'
