name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: "Release edge-agent"
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Tests
        run: npm test

      - name: Detect breaking change
        id: breaking
        run: |
          npx semantic-release --dry-run --no-ci
          echo "result=$(cat .type)" >> $GITHUB_OUTPUT

      - name: Build sdk
        run: |
          npm ci
          npm run build
          
      - name: E2E Tests
        if: ${{ steps.breaking.outputs.result != 'major' }}
        working-directory: integration
        env:
          AGENT_URL: ${{ vars.SIT_AGENT_URL }}
          MEDIATOR_URL: ${{ vars.SIT_MEDIATOR_URL }}
        run: |
          npm ci
          npm run e2e

      - name: Release library
        run: npx semantic-release
